[package]
name = "tenso-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "tenso_rs"
crate-type = ["cdylib", "rlib"]

[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]

[dependencies]
# PyO3 is the bridge between Rust and Python
pyo3 = { version = "0.22", features = ["gil-refs", "abi3-py311"] }
xxhash-rust = { version = "0.8.10", features = ["xxh3"] }
rayon = "1.8"
lz4_flex = "0.11"
libc = "0.2"