/* Tenso C ABI — AUTO-GENERATED by cbindgen from crates/tenso-ffi. DO NOT EDIT BY HAND. */

#ifndef TENSO_H
#define TENSO_H

/* This file is regenerated by `cargo build -p tenso-ffi`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define TENSO_OK 0

#define TENSO_ERR_TOO_SHORT -1

#define TENSO_ERR_BAD_MAGIC -2

#define TENSO_ERR_UNSUPPORTED_VERSION -3

#define TENSO_ERR_BAD_DTYPE -4

#define TENSO_ERR_TOO_MANY_DIMS -5

#define TENSO_ERR_TOO_MANY_ELEMENTS -6

#define TENSO_ERR_INTEGRITY -7

#define TENSO_ERR_BAD_BUNDLE -8

#define TENSO_ERR_LZ4 -9

#define TENSO_ERR_BUFFER_TOO_SMALL -10

#define TENSO_ERR_NULL -11

#define TENSO_ERR_MALFORMED -12

/**
 * A Rust panic was caught at the boundary.
 */
#define TENSO_ERR_PANIC -13

/**
 * Packet is structured (no flat dense body); use a structured decode path.
 */
#define TENSO_ERR_UNSUPPORTED_KIND -14

/**
 * Opaque decoded-view handle. Owns `shape`/`dtype`/`body` so accessor
 * pointers stay valid until `tenso_view_free` (`body` is a fresh allocation).
 */
typedef struct TensoView TensoView;

/**
 * Header view returned through an out-pointer. `#[repr(C)]`, NOT opaque.
 */
typedef struct {
    uint8_t version;
    uint16_t flags;
    uint8_t dtype_code;
    uint32_t ndim;
    uint32_t base_size;
} TensoHeader;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Parse a packet header into `out`. Returns a TENSO_* status code.
 *
 * # Safety
 * `data` must point to `len` readable bytes; `out` must be a valid, writable
 * `TensoHeader`.
 */
 int tenso_parse_header(const uint8_t *data, uintptr_t len, TensoHeader *out) ;

/**
 * Compute the required output size for a dense encode into `*out_size`.
 *
 * # Safety
 * `data`: `data_len` readable bytes; `shape`: `ndim` u32s; `out_size` writable.
 */

int tenso_dense_required_size(const uint8_t *data,
                              uintptr_t data_len,
                              uint8_t dtype_code,
                              const uint32_t *shape,
                              uintptr_t ndim,
                              bool check_integrity,
                              bool compress,
                              uintptr_t alignment,
                              uintptr_t *out_size)
;

/**
 * Encode a dense tensor into a caller-allocated `out` buffer.
 * Writes the byte count to `*written`.
 *
 * # Safety
 * All pointers must be valid; `out` must have `out_cap` writable bytes.
 */

int tenso_encode_dense_into(const uint8_t *data,
                            uintptr_t data_len,
                            uint8_t dtype_code,
                            const uint32_t *shape,
                            uintptr_t ndim,
                            bool check_integrity,
                            bool compress,
                            uintptr_t alignment,
                            uint8_t *out,
                            uintptr_t out_cap,
                            uintptr_t *written)
;

/**
 * Decode a packet to an opaque `TensoView*` (NULL on error; check
 * `tenso_last_error`). Free with `tenso_view_free`. Only flat dense/quantized
 * expose a body; structured kinds yield `TENSO_ERR_UNSUPPORTED_KIND` + NULL.
 *
 * # Safety
 * `data` must point to `len` readable bytes; the view owns its body copy.
 */
 TensoView *tenso_decode(const uint8_t *data, uintptr_t len) ;

/**
 * Dtype code of a decoded view (0 if `view` is null).
 *
 * # Safety
 * `view` must be live from `tenso_decode` or null.
 */
 uint8_t tenso_view_dtype(const TensoView *view) ;

/**
 * Number of dimensions of a decoded view (0 if `view` is null).
 *
 * # Safety
 * `view` must be live from `tenso_decode` or null.
 */
 uintptr_t tenso_view_ndim(const TensoView *view) ;

/**
 * Pointer to the view's shape array (`tenso_view_ndim` u32 entries), or NULL.
 * For 0-d tensors may be non-null but zero-length; gate on `tenso_view_ndim`.
 *
 * # Safety
 * `view` must be live from `tenso_decode` or null; valid until `tenso_view_free`.
 */
 const uint32_t *tenso_view_shape(const TensoView *view) ;

/**
 * Pointer to the view's body bytes, or NULL.
 *
 * # Safety
 * `view` must be live from `tenso_decode` or null; valid until `tenso_view_free`.
 */
 const uint8_t *tenso_view_body_ptr(const TensoView *view) ;

/**
 * Length in bytes of the view's body (0 if `view` is null).
 *
 * # Safety
 * `view` must be live from `tenso_decode` or null.
 */
 uintptr_t tenso_view_body_len(const TensoView *view) ;

/**
 * Free a view returned by `tenso_decode`. No-op on null.
 *
 * # Safety
 * `view` from `tenso_decode`, freed at most once; dangling afterwards.
 */
 void tenso_view_free(TensoView *view) ;

/**
 * Pointer to a thread-local NUL-terminated description of the last error
 * (valid until the next ffi call on this thread); empty `""` (not NULL) if none.
 */
 const char *tenso_last_error(void) ;

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TENSO_H */
